# Numpy Special Operations


In [6]:
import numpy as np

arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [7]:
arr = np.zeros([3,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
arr = np.zeros([3,3],dtype = int)
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [9]:
arr = np.zeros([3,3,3],dtype = int)
arr

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [10]:
arr = np.ones([3],dtype = int)
arr

array([1, 1, 1])

In [11]:
arr = np.ones([3,3,],dtype = int)
arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [12]:
arr = np.full([3,3],7)
arr

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [15]:
arr = np.full([3,3],'digar')
arr

array([['digar', 'digar', 'digar'],
       ['digar', 'digar', 'digar'],
       ['digar', 'digar', 'digar']], dtype='<U5')

In [18]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# Random Number Generation


In [19]:
from numpy import random

In [21]:
a = random.randint(0,100,5)
a

array([22, 24, 71, 85,  2])

In [22]:
a = random.randint(100,size = 10)
a

array([23,  0, 67, 94, 89,  5, 77, 41, 29, 11])

In [23]:
a = random.randint(100,size = [3,3])
a

array([[99, 50, 94],
       [94, 27, 71],
       [77, 61,  0]])

In [25]:
a = random.randint(1000,size = [3,3,3])
a

array([[[734, 188, 988],
        [ 87, 105, 732],
        [653, 532, 749]],

       [[161, 891,  86],
        [654, 532, 268],
        [ 47, 476, 552]],

       [[214, 390, 936],
        [543, 471, 253],
        [166, 189, 708]]])

In [26]:
a = random.rand(5)
a

array([0.91963741, 0.16278666, 0.70646327, 0.92613863, 0.63373939])

In [27]:
a = random.uniform(10000,30000,40)
a

array([22595.12506863, 22078.01887601, 12893.72526856, 16938.8002388 ,
       19430.17385399, 11953.8296664 , 18124.20926678, 11591.78547604,
       29776.12596002, 24491.47721912, 25231.25116262, 19871.83786738,
       14541.40910672, 28847.77907655, 11160.47629927, 19436.67805976,
       17849.56619579, 17570.13151826, 10145.99133818, 16305.57933597,
       19044.9632825 , 24118.8304899 , 25291.04001889, 22240.02836529,
       11407.89745817, 29182.25276234, 17300.43135136, 28065.83702182,
       18222.27226336, 11340.5896828 , 15254.69871559, 12805.13082474,
       10441.38322953, 26723.30628094, 13895.12161132, 27287.40064633,
       18561.17158878, 16256.83773129, 17046.99683871, 24247.26460212])

In [28]:
arr = random.choice([3,4,6,8],size = 5)
arr

array([8, 3, 8, 6, 6])